### ISSUE TITLE
[doc] comparison with arrow IPC

### ISSUE THREAD

**Issue by niyue** [sundy-li/pa#21]
Hi there,

I am an arrow IPC format user, and this is an interesting project, and could you please add some more details about the direction/layout of this storage format, in particular about its comparison with arrow IPC? I have some questions and it would be great if some of them can be clarified in the `README`:
1. The doc says `strawboat is similar to Arrow IPC and is primarily aimed at optimizing the storage layer`, I wonder what the exact optimization is here compared to arrow IPC.
2. Does `is similar to arrow IPC` indicate strawboat is compatible with arrow IPC, or is it just inspired by arrow IPC but no compatibility is guaranteed?
3. In which scenario, strawboat may perform better than arrow IPC? I guess there is probably no benchmark available, but I think it is designed for addressing specific issues that arrow IPC is not a good fit, probably listing the design golas/addressed issues would help as well.
4. arrow IPC is a storage format, which has different language bindings such as C++/Rust/Java that can read/write such a format. Does this repo plan to define a new format and provide other language bindings (it seems only Rust binding is implemented in the repo)?

I know the project is still in early stage, but it would be great for newcomers if some of these can be clarified. Thanks.

**Comment by sundy-li** [comment]
Thanks for the subscription, @niyue 

I have plans to add documents about `strawboat` which convert the storage layout and comparison with IPC or Parquet.

But the storage layout may be refactored since we are working on adding nested datatypes support recently.

I'd like to answer your questions now :)


1. The biggest difference between IPC is that  IPC is a format for memory message or network transmission, so flight SQL can build on it which brings no additional memory conversion overhead.  `strawboat` is similar to IPC , but it is a storage format, it can be read or write from disk with no extra memory overhead.  
There are some other differences between them: 
	- `strawboat` support custom compression on page level and it's using lz4-block API instead of stream API.
    - It has `pages` which can help the reader to skip by page during reading.
    - It's well optimized in reusing the buffer and less memory copy.

3. It's inspired by arrow IPC but not compatible with it.

4. I did not benchmark with IPC because it's not a well-optimized storage format. So the benchmark will be meaningless(IPC did not support pages, so it'll be slower surely). But in databend, we did a benchmark with parquet.  The benchmark is simple:
 
- Here is the performance while adopting to databend https://github.com/datafuselabs/databend/pull/9279
 - we are using clickbench to verify the difference in local fs: https://github.com/ClickHouse/ClickBench/blob/main/databend/create.sql
 - modify the SQL to `Engine = Fuse storage_format = 'native'`, then the table will be created in strawboat format.
 - run the benchmark.
 
 I just benchmark it with the latest databend's version and it can result in a similar performance to ClickHouse which is awesome.

<img width="1819" alt="image" src="https://user-images.githubusercontent.com/3325189/212516917-3e6eb2b7-45f0-4c46-b0e7-53a89f725e3e.png">




 
 We will add more benchmarks in the future.
 
5. > Does this repo plan to define a new format and provide other language bindings 

Yes, we have plans if we make it fully ready in rust implementation, it's so experimental now so we need time to improve that.

**Comment by niyue** [comment]
@sundy-li thanks for the prompt reply.

> help the reader to skip by page during reading

Do you have more details about the `pages`? arrow IPC file allows to store multiple record batches in single file, which can be randomly accessed via the information in footer so record batch can be skipped if needed. Do you think that is similar with `pages` here, or is there any statistic data stored in `pages` which makes them different?

**Comment by sundy-li** [comment]
Yes， it's similar but different.


The page of `strawboat`  is similar to Parquet's page, `page` is the smallest unit of compression. A `column`  contains multi-pages by `max_page_size` option in writing. 

The biggest difference with IPC's `multiple record batches` is that  `Pages` are continuous in a column. 

e.g.:
```
Column A: [1,2,3, 4,5,6]
Column B: ['a', 'b', 'c', 'd', 'e', 'f']
```

in `strawboat`, if `max_page_size` is 3,  its storage layout is:

```
[1,2,3] [4,5,6]  ['a' ,'b', 'c'] ['d', 'e', 'f']
```

And we can have page index later to prune the pages, this is inspired by clickhouse's `granulity` in mergetree.

But in IPC, it will be:
```
[1,2,3] ['a','b','c'][4,5,6]['d', 'e', 'f']
```

IPC's `multiple record batches` is the same as dividing a batch to multiple files.

strawboat can provide faster reading performance in columnar database because IO is in sequence.

**Comment by niyue** [comment]
Ah, I can see that the characteristic `continuous in a column` is missing in arrow IPC. Thanks so much for the detailed explanation, it is very helpful and informative. I will keep an eye on the project and am looking forward to the new updates!
